# This file will transformed into a json-rpc request object and sent to the
# server to its `initialize` request endpoint

root_path = "./coolstore"
analyzer_lsp_java_bundle_path = "./analysis/bundle.jar"
analyzer_lsp_lsp_path = "./analysis/jdtls/bin/jdtls"
analyzer_lsp_rpc_path = "./analysis/kai-analyzer-rpc"
analyzer_lsp_rules_path = "./analysis/rulesets/default/generated"
analyzer_lsp_dep_labels_path = "./analysis/maven.default.index"

demo_mode = true
enable_reflection = false

[log_config]
log_level = "INFO"
file_log_level = "DEBUG"
log_dir_path = "./logs"

[models]
provider = "ChatIBMGenAI"

[models.args]
model_id = "meta-llama/llama-3-1-70b-instruct"
